### ISSUE TITLE
warning while compilling and game wont start

### ISSUE THREAD

**Issue by ZuXeLinc** [trumank/bitfix#4]
This warning in the end of compilling, with this DLL game wont starting: 

warning: method `page_mut` is never used
  --> src\lib.rs:88:8
   |
85 | trait Memory<'memory>: Index<usize, Output = u8> {
   |       ------ method in this trait
...
88 |     fn page_mut<'s>(&'s mut self, index: usize) -> &'s mut Page<'memory>;
   |        ^^^^^^^^
   |
   = note: `#[warn(dead_code)]` on by default

warning: `bitfix` (lib) generated 1 warning
    Finished `release` profile [optimized] target(s) in 1m 36s

![изображение](https://github.com/user-attachments/assets/caca728f-45df-471a-a996-e3a111904583)

**Comment by trumank** [comment]
1. What game?
2. What DLL name are you trying to load as?
3. Is a log file created? (`bitfix.txt`) If so please upload it

**Comment by ZuXeLinc** [comment]
1. Deep Rock Galactic
2. bitfix.dll as d3d9.dll
3. File created, but empty cause game wont launch to apply memory patches

**Comment by trumank** [comment]
That configuration works for me. What OS version (including build ID?) Without a log file or error message there's not much to go on.

**Comment by ZuXeLinc** [comment]
> That configuration works for me. What OS version (including build ID?) Without a log file or error message there's not much to go on.

Windows 10 Pro 22H2 19045.5131

**Comment by ZuXeLinc** [comment]
> That configuration works for me. What OS version (including build ID?) Without a log file or error message there's not much to go on.

Windows 10 Pro 22H2 19045.5131   Game wont laucng, where can i get log file?
compilled dll: [d3d9.zip](https://github.com/user-attachments/files/18088784/d3d9.zip)

**Comment by trumank** [comment]
You will need to step through it with a debugger (WinDbg).
1. I recommend making a debug build (`cargo build --debug`) and then copying `bitfix.dll` AND `bitfix.pdb` from `target/debug/` to the Win64 directory (renaming `bitfix.dll` to `d3d9.dll` like before).
2. Open WinDbg and use "Launch executable" to launch FSD-WindowsNoEditor.exe
3. DRG should start running and break immediately. Clicking on "Go" or "Go to Unhandled Exception" should run until it crashes which should indicate the problem

**Comment by ZuXeLinc** [comment]
No FSD-WindowsNoEditor.exe, maybe u mean FSD-Win64-Shipping.exe. FSD-WindowsNoEditor only "pak" file, not executable
![изображение](https://github.com/user-attachments/assets/fb396a2d-91c6-49ff-b7e0-db7330c5faa3)

**Comment by trumank** [comment]
Please show the full stack and the source of the line immediately before `panic_fmt` if it's there e.g.
![image](https://github.com/user-attachments/assets/ee168719-5bc5-45ce-b8fe-528fff576726)

**Comment by ZuXeLinc** [comment]
![изображение](https://github.com/user-attachments/assets/aa7096b1-6da2-4a0d-9cd7-1354d8f4a69e)

**Comment by trumank** [comment]
It seems to be crashing in a place where crash doesn't seem possible. Since it does seem to actually be creating a panic, it should be possible to get an error message from the console. Here is a build that creates a console window immediately so the panic message should be visible.

[bitfix-console.zip](https://github.com/user-attachments/files/18089757/bitfix-console.zip)

**Comment by ZuXeLinc** [comment]
Game launched...
![изображение](https://github.com/user-attachments/assets/ecdd2c2c-9e21-490b-ad35-61b4f38678f8)

**Comment by ZuXeLinc** [comment]
Maybe something wrong in compilling process?

**Comment by trumank** [comment]
What is your rust version?

**Comment by ZuXeLinc** [comment]
rustc 1.85.0-nightly (33c245b9e 2024-12-10)

**Comment by trumank** [comment]
Just tried building with that version and still no crash. Only other thing I can think of is Windows SDK and MSVC versions, and I have multiple installed so I'm not sure which it's using. For now you can try the release build which is cross compiled from Linux using the GNU target which should sidestep the issue entirely: https://github.com/trumank/bitfix/releases/tag/latest

**Comment by ZuXeLinc** [comment]
Windows 10 SDK 10.0.20348.0 & MSVC 143
But they are unlikely to be the problem

**Comment by ZuXeLinc** [comment]
Well.. Game launched with this compilled DLL: https://github.com/trumank/bitfix/releases/tag/latest
I also tried compilling on linux. In terminal i see "Finished", but have no compilled dll in a directory

**Comment by trumank** [comment]
You need to specify the windows target (and install it if necessary) `--target x86_64-pc-windows-gnu`

**Comment by ZuXeLinc** [comment]
![изображение](https://github.com/user-attachments/assets/166d11da-a0cf-4663-bb85-1f5b2a2f829b)
Rust actually for windows

**Comment by ZuXeLinc** [comment]
It for linux u mean, i tried it for windows

**Comment by ZuXeLinc** [comment]
and it also doesn't work

**Comment by trumank** [comment]
Turns out the problem was simply out of bounds substring on GIT_HASH in the case of git not being installed.

**Comment by ZuXeLinc** [comment]
And what should i do?

**Comment by trumank** [comment]
Fetch latest commit and compile it

**Comment by ZuXeLinc** [comment]
OOO Game launched

**Comment by ZuXeLinc** [comment]
![изображение](https://github.com/user-attachments/assets/1f276728-67b2-4c06-9e6f-a682be2d1fb5)
![изображение](https://github.com/user-attachments/assets/b52ab1b2-4f09-4c5b-9469-ebaf131fb13f)
YEAH IT WORKS

**Comment by ZuXeLinc** [comment]
Thank you very much, trumank
